### ISSUE TITLE
Form.Request throws error in more-1.5.2

### ISSUE THREAD

**Issue by odysseuscm** [mootools/mootools-more#1323] opened 2015-10-09 15:11 UTC
When I build more with Form.Request I get an error upon load:
Uncaught TypeError: (intermediate value)(intermediate value)(...) is not a function
That's the anonymous function that implements QueryString parsing and cleanup (starts in line 1169 when I build only with Form.Request).

**Comment by odysseuscm** [comment] 2015-10-09 15:25
It looks like a dependency bug in the builder. If I manually add Element.Event.Pseudos the error goes away.

**Comment by SergioCrisostomo** [comment] 2015-10-09 15:41
@odysseuscm are you building More with Core or without? `compat` or `nocompat`?

**Comment by odysseuscm** [comment] 2015-10-09 15:42
without Core and nocompat

**Comment by SergioCrisostomo** [comment] 2015-10-09 16:02
@odysseuscm  I can't reproduce your error... 
Please check this jsFiddle with a comment and a link to a build of More I did just now.

**Comment by SergioCrisostomo** [comment] 2015-10-09 16:14
And the jsFiddle :) -> http://jsfiddle.net/9ayufb1v/

**Comment by odysseuscm** [comment] 2015-10-09 16:35
hm. if you add this script in your fiddle: http://kunden.cmcm.info/more/MooTools-More-1.5.2.js
do you get the error? I do.

**Comment by odysseuscm** [comment] 2015-10-09 16:39
You used a complete build of more, didn't you? Try building one with only Form.Request.

**Comment by odysseuscm** [comment] 2015-10-12 08:23
@SergioCrisostomo I'm curious, could you reproduce with a build of Form.Request only?

**Comment by SergioCrisostomo** [comment] 2015-10-13 09:43
@odysseuscm i could reproduce it. Will investigate further, somehow the `;` in [this line](https://github.com/mootools/mootools-more/blob/master/Source/Types/String.QueryString.js#L86) is getting lost. Restoring it fixes the problem.

**Comment by SergioCrisostomo** [comment] 2015-10-24 17:53
Fixed by #1319. We will update the website builder soon.

**Closed by SergioCrisostomo** 2015-10-24 17:53 UTC
Labels: bug
